apiVersion: v1
kind: Service
metadata:
  name: springboot-minikubeapp-service
spec:
  selector:
    app: springboot-minikubeapp
  type: NodePort
  ports:
    - protocol: TCP
      port: 9090
      targetPort: 9090
      nodePort: 30009
